Repository uqfoundation/klepto, pull requests merged in 2023-08, with the labels that each got.

#113 get hash algorithms via `hashlib.algorithms_available`
  klepto/crypto.py
Labels: enhancement

#114 replace negatie with underscore in fname
  klepto/_archives.py
Labels: bugfix

#116 if archive is missing, use null_archive
  klepto/_archives.py
Labels: enhancement

#117 define html_theme as rtd workaround
  docs/source/conf.py
Labels: compatibility
